### ISSUE TITLE
Visual map glitch until window resize

### ISSUE THREAD

**Issue by lesleyrs** [pbellchambers/rustyhack-mmo#113]
**Describe the bug**
Whenever you load `rustyhack_client` visually the map doesn't load correctly until you resize window.

It doesn't seem to happen if you play on maximized window.

**To Reproduce**
1. load client
2. look at distorted map

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/19632758/217551323-c1043f88-a01b-49bb-bccd-25f6b6387a25.png)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
Add any other context about the problem or logfiles related to the problem here.

btw is it possible to access the other maps yet?

**Comment by lesleyrs** [comment]
I think this is an upstream problem because yesterday I reported some bugs in at `crossterm` about screen resizing. Also on the normal Conshole host this screen problem doesn't happen but then you get the blinking cursor like you mentioned in projects tab.

**Comment by pbellchambers** [comment]
I can reproduce this on windows 11 but only with the terminal host and not windows console host. I can't see anything in this project that would cause it (or fix it), so I assume it's an upstream issue. I'll keep this open though.

To answer your other questions:
- The blinking cursor issue on terminal host after resizing was resolved with a recent console_engine update, I haven't made a new release yet, but the dependency is already updated in main
- The window resizing and showing more of the map is deliberate at the moment, no plans to change that.
- I will be working on accessing other maps next, haven't had much time to do anything with this recently.

**Comment by lesleyrs** [comment]
Cool, don't worry about my issues. I'm just going through various terminal projects to see what the limitations are. If I come across this myself I'll be back.
