### ISSUE TITLE
When you force close a client terminal the server gets flooded with errors and lags a bit

### ISSUE THREAD

**Issue by lesleyrs** [pbellchambers/rustyhack-mmo#114]
**Describe the bug**
Server doesn't handle force quits well.

**To Reproduce**
1. ctrl+shift+w a client
2. look server log

**Expected behavior**
I expected it to work the same as ctrl-q

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
`[ERROR] Encountered an error receiving data: Os { code: 10054, kind: ConnectionReset`

I was able to do a pvp battle with myself at least, so that's cool 🗡️

**Comment by lesleyrs** [comment]
Similar problems are trying to run a server with one already active gets stuck loading. Same with running a client with no active server.

**Comment by pbellchambers** [comment]
Yeah, this is something I'm aware of, and error handling in general I've not put much effort into yet.
