### ISSUE TITLE
Multiplatform (Android)

### ISSUE THREAD

**Issue by RickyZimmermann** [pbellchambers/rustyhack-mmo#183]
**Feature request**
I realy would like to see this on android.
Compiling it doesnt seem to create an apk.

Only scripts are returning so not a working app.
There is some code needed to get it working on mobile.

(Also for windows it gave a lot of compile errors so it wasnt working. There is no describtion about what versions of all software is needed to compile this game.)

**Solution**
1.Add some code so it can be run on android.
2. Controls can be a emu, or virtual round drag buttons.

Should not be hard to make.

Add a "howto compile" file in your project.
That would make things easier in the future.
Almost all open source projects are missing version numbers of the compilers that are used.

**Comment by pbellchambers** [comment]
It's unlikely this will ever work on Android, as it's a terminal application. It will only run on platforms that [crossterm-rs](https://github.com/crossterm-rs/crossterm) supports. It might be possible to install [Termux](https://termux.dev/en/) on Android, then install rust, and then try checking out and building this project, but I doubt this would actually work (it also would not be an APK).

Regarding building the application, the steps are:
1. Install latest version of [rust](https://www.rust-lang.org/) (latest version confirmed working `1.76.0`)
2. Download this repository
3. Run `cargo build` in the repository root directory
4. Copy `assets` directory into `target/debug` directory
5. Run `rustyhack_server` and `rustyhack_client` from `target/debug` directory

These steps are defined in the github build actions configuration for the project ([.github/workflows/main.yml](https://github.com/pbellchambers/rustyhack-mmo/blob/main/.github/workflows/main.yml)). The build results for Windows, Mac, and Ubuntu for every commit can be seen [here](https://github.com/pbellchambers/rustyhack-mmo/actions).

For clarity, I've added the steps to the readme now.
