### ISSUE TITLE
Maps dont load.

### ISSUE THREAD

**Issue by RickyZimmermann** [pbellchambers/rustyhack-mmo#192]
**Describe the bug**
If you walk to a entrance (for example the enterance in the graveyard), it does nothing.

**To Reproduce**
1. Go to 'x:5 y:28' 
2. Nothing happens

**Expected behavior**
Spawn into another map.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by pbellchambers** [comment]
The `m` key should change maps when standing over a map exit.
